### ISSUE TITLE
Recognize templates in YAML format

### ISSUE THREAD

**Issue by ash2k** [shalupov/idea-cloudformation#55]
Similar to #49; we have some templates in YAML format and it would be nice to have support for such templates. We find templates in YAML to be more readable so we started to use it to write templates a while ago. The plugin will need to check if files with `.yml`/`.yaml` extension are CloudFormation templates. WDYT?

**Comment by shalupov** [comment]
No immediate plans. but it should not be too hard

**Comment by ash2k** [comment]
CloudFormation now supports YAML natively https://aws.amazon.com/about-aws/whats-new/2016/09/aws-cloudformation-introduces-yaml-template-support-and-cross-stack-references/

**Comment by darken99** [comment]
Please add this feature as Amazon now officially supports YAML and according to my tests YAML saves 20% size comparing to JSON.

**Comment by warrenronsiek** [comment]
+1

**Comment by jyrkih** [comment]
+1

**Comment by sampritavh** [comment]
+1

**Comment by sihil** [comment]
+1

**Comment by schickling** [comment]
+1

**Comment by jdesulme** [comment]
+1

**Comment by Christoph-Schabert** [comment]
+1

**Comment by niklasastrom** [comment]
+1

**Comment by philmcmahon** [comment]
+1

**Comment by simon-morgan** [comment]
+1

**Comment by gabeng** [comment]
+1

**Comment by bitsal** [comment]
+1

**Comment by arifwider** [comment]
+1

**Comment by schickling** [comment]
@shalupov considering that "it should not be too hard" and a lot of people seem to really want this feature: are there any updates or plans?

**Comment by shalupov** [comment]
"it should not be too hard" in this context unfortunately means rewrite all language-dependent code, which is still not too hard, but requires at least several full days.

**Comment by samm0ss** [comment]
+1

**Comment by nickjwebb** [comment]
Let's put our money where our mouths are, I have $100 if that will help @shalupov . Perhaps we can setup something via this site or the like:
https://www.bountysource.com/

**Comment by hoegertn** [comment]
Done: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=32437649)](https://www.bountysource.com/issues/32437649-recognize-templates-in-yaml-format?utm_source=32437649&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by shalupov** [comment]
Thank you for your support! I don't think I'm ready for money relations in this way, at least yet.

I'll try to implement YAML this year.

**Comment by anttimaula-fsc** [comment]
This would be so cool feature since we are also using YAML for stacks more and more. 

+1

**Comment by shalupov** [comment]
Development of YAML support was started previous year, but not yet finished. For curious it's in yaml branch

**Comment by danieljimenez** [comment]
Upped the bounty: [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=32437649)](https://www.bountysource.com/issues/32437649-recognize-templates-in-yaml-format?utm_source=32437649&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by bbergstrom** [comment]
+1

**Comment by hoegertn** [comment]
I tried to install the version from the yaml branch but I got the following exception on startup.

```
java.lang.NoClassDefFoundError: org/jetbrains/yaml/YAMLLanguage
    at com.intellij.aws.cloudformation.YamlCloudFormationFileType.<init>(YamlCloudFormationFileType.kt:14)
    at com.intellij.aws.cloudformation.YamlCloudFormationFileType.<clinit>(YamlCloudFormationFileType.kt:37)
    at com.intellij.aws.cloudformation.CloudFormationFileTypeFactory.createFileTypes(CloudFormationFileTypeFactory.kt:9)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:312)
    at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:272)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:69)
```

**Comment by shalupov** [comment]
@hoegertn What's your IDE? YAML plugin is required for all of this and it's usually bundled, it least in community edition IDEA. Please check it's not disabled

**Comment by danieljimenez** [comment]
I received the same, FWIW.

**Comment by hoegertn** [comment]
@shalupov any idea on this. Would love to try the YAML version. Plugin is on and I have the Ultimate version.

**Comment by shalupov** [comment]
@hoegertn @danieljimenez fixed it. So, format checking and references resolving mostly ok and ready for testing. Completion works sometimes and not ready for testing, everything else is missing

**Comment by shalupov** [comment]
I've released 0.5.3 version with initial YAML support: format checking and references resolving works. Completion works sometimes and not ready for testing, everything else is missing.

0.5.x plugin will track IDEA 2017.1 EAP, so you need latest EAP to try it, download it from https://www.jetbrains.com/idea/nextversion/ or via Toolbox App.

**Comment by schickling** [comment]
@shalupov any news when this update will official land?

**Comment by shalupov** [comment]
I believe YAML support in v0.5.19 is on par with JSON one (you need IDEA 2017.1 or later).
So closing this issue.
Please file separate issues for any bugs and missing features in YAML support.

Thanks you for the waiting and let's meet again in other issues.

**Comment by hoegertn** [comment]
@shalupov you can still claim the bounty. The money is there lying around ;-)

**Comment by danieljimenez** [comment]
@shalupov I haven't tested yet, but you deserve the money. I vote you take it.

**Comment by danieljimenez** [comment]
Anything I need to do to get Intellij to recognize the YAML? I was just about to vote to release the bounty.

**Comment by nickjwebb** [comment]
Make sure you start your template with something like:
```
---
AWSTemplateFormatVersion: '2010-09-09'
```

That does it for me.

**Comment by danieljimenez** [comment]
Didn't work for me, but I'll play with it a bit later. Thanks!

**Comment by schickling** [comment]
Doesn't work for me either. The file looks like this `stack.yaml`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: '...'
Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: '10.0.0.0/16'
      Tags:
      - Key: 'Name'
        Value: !Ref AWS::StackName
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: 'eu-west-1a'
      VpcId: !Ref Vpc
      CidrBlock: '10.0.0.0/24'
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
      - Key: 'Name'
        Value: !Sub '${AWS::StackName}-public'

```

**Comment by neowulf33** [comment]
The following worked for me:

1. Rename cloudformation yaml files with this pattern - `*_cf.yaml`.
2. IntelliJ > Preferences > Editor > File Types
3. Associating "AWS Cloudformation Templates (YAML)" with `*_cf.yaml`

Although, it'd be nice to apply an intellij facet to a directory for auto detection of cloudformation templates.

**Comment by neowulf33** [comment]
Another way was to create a new file with the option - "AWS Cloudformation Template". However, this gets restricted to a JSON file.

**Comment by shalupov** [comment]
please check version 0.3.54, I've made another fix for auto-detection

**Comment by danieljimenez** [comment]
@shalupov Hmm, I'm running `0.5.30`, did you perhaps mean `0.5.34`?

**Comment by shalupov** [comment]
@danieljimenez yes, 0.3.34, thanks
(https://plugins.jetbrains.com/plugin/7371-aws-cloudformation/update/37311)

**Comment by peterbarber** [comment]
using AWS Cloudformation 0.5.41 - I've maped *.template to AWS Cloudformation YAML.
But recognised file type as JSON. Renaming file extension to .yaml seems to recognise as AWS Cloudformation YAML. 

Thanks Pete
